# Generated by Django 4.1.7 on 2023-02-15 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earlkit', '0004_alter_earlkit_img_alter_earlkit_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earlkit',
            name='desc',
            field=models.TextField(default='', help_text='please enter a description for the site', max_length=500),
        ),
        migrations.AlterField(
            model_name='earlkit',
            name='tags',
            field=models.TextField(default='', help_text='please seperate all tags with a colon (ex tag1 : tag2)', max_length=30),
        ),
    ]
