# Generated by Django 4.1.7 on 2023-02-23 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earlkit', '0012_alter_earlkit_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earlkit',
            name='uid',
            field=models.UUIDField(default='5511087566664d41b20a5aaa8aecea92', editable=False, unique=True),
        ),
    ]
