# Generated by Django 4.1.7 on 2023-02-15 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Earlkit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(auto_created=True)),
                ('title', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=500)),
                ('img', models.CharField(max_length=100)),
                ('tags', models.CharField(max_length=200)),
            ],
        ),
    ]
