# Generated by Django 4.1.7 on 2023-02-15 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earlkit', '0005_alter_earlkit_desc_alter_earlkit_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earlkit',
            name='desc',
            field=models.TextField(default='', help_text='Please enter a description for the site\nMax 500 characters', max_length=500),
        ),
        migrations.AlterField(
            model_name='earlkit',
            name='tags',
            field=models.TextField(default='', help_text='Please seperate all tags with a colon (ex tag1 : tag2)\nMax 30 characters', max_length=30),
        ),
    ]
