# Generated by Django 4.1.7 on 2023-02-15 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earlkit', '0006_alter_earlkit_desc_alter_earlkit_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earlkit',
            name='tags',
            field=models.CharField(default='', help_text='Please seperate all tags with a colon (ex tag1 : tag2)\nMax 30 characters', max_length=30),
        ),
    ]
