# Generated by Django 4.1.7 on 2023-02-16 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earlkit', '0007_alter_earlkit_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earlkit',
            name='img',
            field=models.ImageField(max_length=256, upload_to='../../public/images/'),
        ),
    ]
