# Generated by Django 4.1.7 on 2023-02-16 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earlkit', '0008_alter_earlkit_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earlkit',
            name='img',
            field=models.ImageField(max_length=256, upload_to='images/'),
        ),
    ]
