# Generated by Django 4.1.7 on 2023-02-23 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earlkit', '0010_alter_earlkit_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earlkit',
            name='uid',
            field=models.UUIDField(default='649afedb01fe4b9b8fbf2e27a30660d0', editable=False, unique=True),
        ),
    ]
