# Generated by Django 4.1.7 on 2023-02-23 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earlkit', '0011_alter_earlkit_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earlkit',
            name='uid',
            field=models.UUIDField(default='91e588357fe141ddbcc330b4b4dbd4df', editable=False, unique=True),
        ),
    ]
