# Generated by Django 4.1.7 on 2023-02-23 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earlkit', '0013_alter_earlkit_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earlkit',
            name='uid',
            field=models.CharField(default='90abb39034d34d9f802262d14642536b', editable=False, max_length=15, unique=True),
        ),
    ]
