# Generated by Django 4.1.7 on 2023-02-23 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earlkit', '0014_alter_earlkit_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earlkit',
            name='uid',
            field=models.CharField(default='c14cb8eb2825441d84f9ff37d913c828', editable=False, max_length=15, unique=True),
        ),
    ]
