# Generated by Django 4.1.7 on 2023-03-28 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earlkit', '0015_alter_earlkit_uid'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisualizerSwitchList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(default='d514e20984854cb5a6ff5d6d3f3fde70', editable=False, max_length=15, unique=True)),
                ('switch', models.CharField(max_length=50)),
                ('bldg', models.CharField(max_length=100)),
                ('room', models.CharField(max_length=50)),
                ('rack', models.CharField(max_length=50)),
                ('panel', models.CharField(max_length=50)),
                ('u', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='earlkit',
            name='uid',
            field=models.CharField(default='5e7146be4f8748b1b49ada3a7573a3af', editable=False, max_length=15, unique=True),
        ),
    ]
