# Generated by Django 4.1.7 on 2023-03-28 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earlkit', '0016_visualizerswitchlist_alter_earlkit_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earlkit',
            name='uid',
            field=models.CharField(default='be314dc53d7d4242b1972472fd443c1c', editable=False, max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='visualizerswitchlist',
            name='uid',
            field=models.CharField(default='95a9e824cd5b464cb6f1fdd1dbe75765', editable=False, max_length=15, unique=True),
        ),
    ]
