# Generated by Django 4.1.7 on 2023-03-28 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earlkit', '0017_alter_earlkit_uid_alter_visualizerswitchlist_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earlkit',
            name='uid',
            field=models.CharField(default='d26d357b8ce3410686472faa4d41d6f8', editable=False, max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='visualizerswitchlist',
            name='uid',
            field=models.CharField(default='79dab36ec37744bd8d987c92add43b24', editable=False, max_length=15, unique=True),
        ),
    ]
