# Generated by Django 4.1.7 on 2023-03-28 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earlkit', '0019_alter_earlkit_uid_alter_visualizerswitchlist_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earlkit',
            name='uid',
            field=models.CharField(default='c443591dbad548c785911ad031183f43', editable=False, max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='visualizerswitchlist',
            name='uid',
            field=models.CharField(default='214d8138316c4f3b9572da454098e7bd', editable=False, max_length=15, unique=True),
        ),
    ]
