# Generated by Django 4.1.7 on 2023-03-28 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earlkit', '0020_alter_earlkit_uid_alter_visualizerswitchlist_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='visualizerswitchlist',
            name='devtype',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='visualizerswitchlist',
            name='ios',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='visualizerswitchlist',
            name='mgmtip',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='visualizerswitchlist',
            name='sn',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='earlkit',
            name='uid',
            field=models.CharField(default='8a2753df82ef4d3c86c88ed87c9da0b5', editable=False, max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='visualizerswitchlist',
            name='uid',
            field=models.CharField(default='eb43dac839a5487abd5b550da1dfedb4', editable=False, max_length=15, unique=True),
        ),
    ]
