# Generated by Django 4.1.7 on 2023-03-28 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earlkit', '0021_visualizerswitchlist_devtype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earlkit',
            name='uid',
            field=models.CharField(default='aa0f947fff3e4bffb794f12b710d36dd', editable=False, max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='visualizerswitchlist',
            name='uid',
            field=models.CharField(default='1c161517b28540d291f4ef7797aa8550', editable=False, max_length=15, unique=True),
        ),
    ]
