# Generated by Django 4.1.7 on 2023-03-28 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earlkit', '0022_alter_earlkit_uid_alter_visualizerswitchlist_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visualizerswitchlist',
            name='uid',
        ),
        migrations.AddField(
            model_name='visualizerswitchlist',
            name='switchuid',
            field=models.CharField(default='916ebecc9efb429b99ebc883f58b5be4', editable=False, max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='earlkit',
            name='uid',
            field=models.CharField(default='91a2942f48b446289486688f66b60e75', editable=False, max_length=15, unique=True),
        ),
    ]
