# Generated by Django 4.1.7 on 2023-03-29 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earlkit', '0023_remove_visualizerswitchlist_uid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visualizerswitchlist',
            name='id',
        ),
        migrations.AlterField(
            model_name='earlkit',
            name='uid',
            field=models.CharField(default='f624788e351e45e4a5f0df8b8017d7af', editable=False, max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='visualizerswitchlist',
            name='switchuid',
            field=models.UUIDField(default='0c05825cb4e2454fab034f92eba55c9e', editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
