# Generated by Django 4.1.7 on 2023-03-29 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earlkit', '0028_alter_earlkit_uid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earlkit',
            name='uid',
            field=models.CharField(default='f164f56c2bec40799daa284bd86e7bce', editable=False, max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='visualizerswitchlist',
            name='switchuid',
            field=models.CharField(default='ff97ee4ced344a5bb32f615e891e5dca', editable=False, max_length=15, primary_key=True, serialize=False, unique=True),
        ),
    ]
