# Generated by Django 4.1.7 on 2023-03-29 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earlkit', '0029_alter_earlkit_uid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earlkit',
            name='uid',
            field=models.CharField(default='4c97eba60666410d80740dbaa2484354', editable=False, max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='visualizerswitchlist',
            name='switchuid',
            field=models.CharField(default='b7667d80ba8a41a5a3e777326ada3afb', editable=False, max_length=15, primary_key=True, serialize=False),
        ),
    ]
