# Generated by Django 4.1.7 on 2023-04-01 21:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('earlkit', '0031_alter_earlkit_uid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisualizerInterfaceList',
            fields=[
                ('switchInterfaceUID', models.CharField(default=uuid.uuid4, editable=False, max_length=15, primary_key=True, serialize=False, unique=True)),
                ('interface', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('verified', models.CharField(max_length=50)),
                ('swportmode', models.CharField(max_length=50)),
                ('admindown', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='earlkit',
            name='uid',
            field=models.CharField(default='bde806b25f9940199b1032726ba04371', editable=False, max_length=15, unique=True),
        ),
    ]
