# Generated by Django 4.1.7 on 2023-04-01 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earlkit', '0032_visualizerinterfacelist_alter_earlkit_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='visualizerinterfacelist',
            name='hostname',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='earlkit',
            name='uid',
            field=models.CharField(default='4129e065ce6b47a88162c6ad6bba68e6', editable=False, max_length=15, unique=True),
        ),
    ]
