# Generated by Django 4.1.7 on 2023-04-01 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earlkit', '0033_visualizerinterfacelist_hostname_alter_earlkit_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earlkit',
            name='uid',
            field=models.CharField(default='a76fe7ddfffc451883b96a40874d0b88', editable=False, max_length=15, unique=True),
        ),
    ]
