# Generated by Django 4.1.7 on 2023-04-04 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earlkit', '0035_alter_earlkit_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earlkit',
            name='uid',
            field=models.CharField(default='2a2ff964629e482788917a97b4485670', editable=False, max_length=15, unique=True),
        ),
    ]
