# Generated by Django 4.1.7 on 2023-04-05 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earlkit', '0036_alter_earlkit_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earlkit',
            name='uid',
            field=models.CharField(default='e7915184aec3429bb96772bef0d352ea', editable=False, max_length=15, unique=True),
        ),
    ]
